version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
